<?php

include_once("index.html");
include_once("about.html");
include_once("category.html");
include_once("porkrecipe.html");
include_once("view.html");
include_once("view1.html");
include_once("view2.html");
include_once("view3.html");
include_once("chickenrecipe.html");
include_once("curry.html");
include_once("bbq.html");
include_once("pastel.html");
include_once("fishrecipe.html");
include_once("inihaw.html");
include_once("tilapia.html");
include_once("vegie.html");
include_once("pinakbet.html");
include_once("chopseuy.html");
include_once("sitaw.html");
include_once("negosyo.html");
include_once("yemaballs.html");
include_once("turon.html");
include_once("bananaque.html");
include_once("lecheflan.html");
include_once("contact.html");

?>
